import {useEffect,useMemo,useState} from "react";
import {useLibrary} from "../../library/LibraryContext";
import {usePlayback} from "../../audio/PlaybackContext";
import {searchOpenMusic} from "../../lib/openverse";
import {Icon} from "../../components/ui/Icon";
import type {Track} from "../../types";
import {saveTrack} from "../../lib/db";
const readRecent=():string[]=>{try{const x=JSON.parse(localStorage.getItem("mfa:searches")||"[]");return Array.isArray(x)?x:[]}catch{return[]}};
export function SearchPage({query,setQuery}:{query:string;setQuery:(v:string)=>void}){
 const l=useLibrary(),p=usePlayback(),[mode,setMode]=useState<"library"|"open">("library"),[open,setOpen]=useState<Track[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[recent,setRecent]=useState(readRecent);
 const local=l.ordered.filter(t=>(t.title+" "+t.artist+" "+t.album).toLowerCase().includes(query.toLowerCase())).slice(0,40);
 const trending=useMemo(()=>Array.from(new Map(l.ordered.map(t=>[t.artist,t])).values()).slice(0,4),[l.ordered]);
 const remember=(q:string)=>{const v=q.trim();if(!v)return;const next=[v,...recent.filter(x=>x.toLowerCase()!==v.toLowerCase())].slice(0,8);setRecent(next);localStorage.setItem("mfa:searches",JSON.stringify(next))};
 useEffect(()=>{if(mode!=="open"||!query.trim()){setOpen([]);setBusy(false);return}setBusy(true);setError(null);searchOpenMusic(query.trim()).then(setOpen).catch(()=>{setOpen([]);setError("Open Music search is unavailable right now.")}).finally(()=>setBusy(false))},[mode,query]);
 const download=async(t:Track)=>{if(!t.audioUrl)return;remember(query);setError(null);setBusy(true);try{const r=await fetch(t.audioUrl);if(!r.ok)throw new Error();const blob=await r.blob();if(!blob.size)throw new Error();const id=crypto.randomUUID(),blobId=crypto.randomUUID();await saveTrack({...t,id,blobId,addedAt:Date.now(),duration:t.duration},blob);await l.refresh()}catch{setError("Could not import that open track. The source may block browser downloads.")}finally{setBusy(false)}};
 const playLocal=(t:Track)=>{remember(query);void p.play(t)};
 return <div className="page"><div className="search-page-head"><small>SEARCH</small><h1>Find something.</h1><label><Icon name="search"/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Songs, artists, albums..."/></label></div>
  {!query.trim()&&!l.tracks.length?<><section className="search-block"><div className="section-line"><span>Recent Searches</span>{recent.length>0&&<button onClick={()=>{setRecent([]);localStorage.removeItem("mfa:searches")}}>Clear</button>}</div><div className="recent-searches">{recent.length?recent.map(x=><button key={x} onClick={()=>setQuery(x)}><Icon name="clock" size={11}/>{x}</button>):<span className="muted-copy">Your searches will appear here.</span>}</div></section><section className="search-block"><div className="section-line"><span>Trending Now</span></div><div className="trend-grid">{trending.length?trending.map((t,i)=><button key={t.id} className={"trend-card t"+i} onClick={()=>setQuery(t.artist)}><b>{t.artist}</b><small>{t.album}</small></button>):["Artists","Albums","Playlists","Local Music"].map((x,i)=><button key={x} className={"trend-card t"+i} onClick={()=>setQuery(x)}><b>{x}</b><small>Search your library</small></button>)}</div></section></>:
  <><div className="segmented"><button className={mode==="library"?"active":""} onClick={()=>setMode("library")}>My library</button><button className={mode==="open"?"active":""} onClick={()=>setMode("open")}>Open Music</button></div>{error&&<div className="player-error">{error}</div>}{mode==="library"?<div className="library-list">{local.map(t=><button className="library-row" key={t.id} onClick={()=>playLocal(t)}><span><strong>{t.title}</strong><small>{t.artist} · {t.album}</small></span><Icon name="play" size={16}/></button>)}{!local.length&&<div className="empty-state"><h3>No local matches</h3><p>Try Open Music for public-domain and CC0 sources.</p></div>}</div>:<div className="library-list">{busy?<div className="empty-state"><p>Searching public sources…</p></div>:open.map(t=><button className="library-row" key={t.id} onClick={()=>void download(t)}><span><strong>{t.title}</strong><small>{t.artist} · {t.provider||"Openverse"}</small></span><Icon name="download" size={16}/></button>)}</div>}</>}
 </div>
}