import {createContext,useCallback,useContext,useEffect,useMemo,useRef,useState,type ReactNode} from "react";import type {StoredTrack} from "../types";import {getBlob,updateTrackMetadata,useLibrary} from "../library/LibraryContext";import {MuseflixAudioEngine,DEFAULT_EQUALIZER,type EqualizerState} from "../lib/equalizer";
type Repeat="off"|"all"|"one";type PlaybackValue={current:StoredTrack|null;playing:boolean;time:number;queue:StoredTrack[];shuffle:boolean;repeat:Repeat;sleepTimer:number|null;toggle:()=>Promise<void>;play:(t:StoredTrack,reset?:boolean)=>Promise<void>;next:()=>Promise<void>;previous:()=>Promise<void>;seek:(n:number)=>void;setShuffle:(v:boolean)=>void;cycleRepeat:()=>void;cycleSleepTimer:()=>void;openQueue:()=>void;closeQueue:()=>void;queueOpen:boolean};
const C=createContext<PlaybackValue|null>(null);
export function PlaybackProvider({children}:{children:ReactNode}){const{ordered,refresh}=useLibrary();const[current,setCurrent]=useState<StoredTrack|null>(null),[playing,setPlaying]=useState(false),[time,setTime]=useState(0),[queue,setQueue]=useState<StoredTrack[]>([]),[shuffle,setShuffle]=useState(false),[repeat,setRepeat]=useState<Repeat>("off"),[sleepTimer,setSleepTimer]=useState<number|null>(null);const[queueOpen,setQueueOpen]=useState(false),audio=useRef(new Audio()),engine=useRef(new MuseflixAudioEngine()),url=useRef<string|null>(null),eq=useRef<EqualizerState>(DEFAULT_EQUALIZER);
useEffect(()=>{try{const x=JSON.parse(localStorage.getItem("mfa:eq")||"null");if(x&&Array.isArray(x.bands))eq.current=x}catch{}},[]);
const play=useCallback(async(t:StoredTrack,reset=true)=>{const blob=await getBlob(t.blobId);if(!blob)return;if(url.current)URL.revokeObjectURL(url.current);url.current=URL.createObjectURL(blob);audio.current.src=url.current;audio.current.load();engine.current.connect(audio.current);engine.current.setState(eq.current);setCurrent(t);setTime(0);if(reset){const i=ordered.findIndex(x=>x.id===t.id);setQueue(ordered.slice(i+1))}setQueue(q=>q.filter(x=>x.id!==t.id));setRecent(t.id);await updateTrackMetadata(t.id,{playCount:(t.playCount||0)+1});await refresh();try{await engine.current.resume(audio.current);await audio.current.play()}catch{}},[ordered,refresh]);
const setRecent=(id:string)=>{const raw=(()=>{try{return JSON.parse(localStorage.getItem("mfa:recent")||"[]")}catch{return[]}})() as string[];localStorage.setItem("mfa:recent",JSON.stringify([id,...raw.filter(x=>x!==id)].slice(0,30)))};
const next=useCallback(async()=>{if(!current||!ordered.length)return;if(repeat==="one"){audio.current.currentTime=0;await audio.current.play();return}if(queue.length){const n=queue[0];setQueue(q=>q.slice(1));await play(n,false);return}let n:StoredTrack|undefined;if(shuffle){const pool=ordered.filter(t=>t.id!==current.id);n=pool[Math.floor(Math.random()*pool.length)]}else{const i=ordered.findIndex(t=>t.id===current.id);if(repeat==="off"&&i===ordered.length-1){setPlaying(false);return}n=ordered[(i+1+ordered.length)%ordered.length]}if(n)await play(n,false)},[current,ordered,repeat,queue,shuffle,play]);
const previous=useCallback(async()=>{if(audio.current.currentTime>3){audio.current.currentTime=0;return}if(!current)return;const i=ordered.findIndex(t=>t.id===current.id),n=ordered[(i-1+ordered.length)%ordered.length];if(n)await play(n,false)},[current,ordered,play]);
useEffect(()=>{const a=audio.current,onPlay=()=>setPlaying(true),onPause=()=>setPlaying(false),onTime=()=>setTime(a.currentTime||0),onEnd=()=>void next();a.addEventListener("play",onPlay);a.addEventListener("pause",onPause);a.addEventListener("timeupdate",onTime);a.addEventListener("ended",onEnd);return()=>{a.removeEventListener("play",onPlay);a.removeEventListener("pause",onPause);a.removeEventListener("timeupdate",onTime);a.removeEventListener("ended",onEnd)}},[next]);
useEffect(()=>{if(sleepTimer===null)return;const id=setInterval(()=>setSleepTimer(v=>{if(v===null)return null;if(v<=1){audio.current.pause();return null}return v-1}),1000);return()=>clearInterval(id)},[sleepTimer]);useEffect(()=>()=>{if(url.current)URL.revokeObjectURL(url.current)},[]);
const toggle=useCallback(async()=>{if(!current){if(ordered[0])await play(ordered[0]);return}if(audio.current.paused)await audio.current.play().catch(()=>{});else audio.current.pause()},[current,ordered,play]);const seek=(n:number)=>{audio.current.currentTime=n;setTime(n)};const cycleRepeat=()=>setRepeat(v=>v==="off"?"all":v==="all"?"one":"off");const cycleSleepTimer=()=>setSleepTimer(v=>v===null?600:v===600?1200:v===1200?1800:v===1800?3600:null);const value=useMemo(()=>({current,playing,time,queue,shuffle,repeat,sleepTimer,toggle,play,next,previous,seek,setShuffle,cycleRepeat,cycleSleepTimer,openQueue:()=>setQueueOpen(true),closeQueue:()=>setQueueOpen(false),queueOpen}),[current,playing,time,queue,shuffle,repeat,sleepTimer,toggle,play,next,previous]);return <C.Provider value={value}>{children}</C.Provider>}
export function usePlayback(){const v=useContext(C);if(!v)throw new Error("usePlayback must be used inside PlaybackProvider");return v}