import {useEffect,useMemo,useRef,useState} from "react";
import type {ChangeEvent,ReactNode} from "react";
import type {StoredTrack,Tab,Track} from "./types";
import {deleteTrack,getBlob,listTracks,saveTrack} from "./lib/db";
import {searchOpenMusic} from "./lib/openverse";

type RepeatMode="off"|"all"|"one";
type ViewMode="songs"|"albums"|"artists";

const Icon=({n,s=20}:{n:string;s?:number})=>{
 const d:Record<string,string>={
  home:"M3 10.5 12 3l9 7.5v9a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1z",search:"M10.5 4a6.5 6.5 0 1 0 0 13 6.5 6.5 0 0 0 0-13ZM16 16l5 5",library:"M4 5.5h16v13H4zM8 9h8M8 13h8M8 17h5",settings:"M12 8.5a3.5 3.5 0 1 0 0 7 3.5 3.5 0 0 0 0-7ZM12 3v2M12 19v2M3 12h2M19 12h2M5.6 5.6 7 7M17 17l1.4 1.4M18.4 5.6 17 7M7 17l-1.4 1.4",play:"M8 5v14l11-7z",pause:"M7 5h4v14H7zM13 5h4v14h-4z",next:"M5 5v14l9-7zM18 5v14",prev:"M19 5v14l-9-7zM6 5v14",heart:"M20.8 8.9c0 5.5-8.8 10.1-8.8 10.1S3.2 14.4 3.2 8.9A5 5 0 0 1 12 5.4a5 5 0 0 1 8.8 3.5",queue:"M4 6h11M4 12h11M4 18h7m5-3 4 3-4 3",plus:"M12 5v14M5 12h14",back:"m15 5-7 7 7 7",close:"M6 6l12 12M18 6 6 18",shuffle:"M4 7h3c4 0 5 10 10 10h3M4 17h3c1.5 0 2.5-1.2 3.3-2.5M17 4l3 3-3 3M17 14l3 3-3 3",repeat:"M17 2l3 3-3 3M4 5h16v6M7 22l-3-3 3-3M20 19H4v-6",more:"M12 5h.01M12 12h.01M12 19h.01",clock:"M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18ZM12 7v5l3 2",download:"M12 3v12m0 0 4-4m-4 4-4-4M5 21h14",trash:"M5 7h14m-9 4v6m4-6v6M9 7V4h6v3m-9 0 1 14h10l1-14"
 };
 return <svg width={s} height={s} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d={d[n]||d.more}/></svg>;
};

const Art=({t,large=false}:{t?:Track;large?:boolean})=>{
 const seed=(t?.title||"Music").split("").reduce((a,c)=>a+c.charCodeAt(0),0)%10;
 if(t?.artworkUrl)return <div className={"art art-image"+(large?" large":"")}><img src={t.artworkUrl} alt="" loading="lazy"/></div>;
 return <div className={"art art-"+seed+(large?" large":"")}><span>{(t?.title||"M").charAt(0).toUpperCase()}</span></div>;
};
const fmt=(n=0)=>Number.isFinite(n)&&n>=0?Math.floor(n/60)+":"+String(Math.floor(n%60)).padStart(2,"0"):"—";
const stored=(k:string)=>{try{const x=JSON.parse(localStorage.getItem(k)||"[]");return Array.isArray(x)?x:[]}catch{return[]}};
const uid=()=>crypto.randomUUID?.()||String(Date.now()+Math.random());
const parseFilename=(name:string)=>{const clean=name.replace(/\.[^.]+$/,"").replace(/[_]+/g," ").trim();const p=clean.split(/\s+-\s+/);return p.length>1?{artist:p[0].trim()||"Unknown artist",title:p.slice(1).join(" - ").trim()||clean||"Untitled"}:{artist:"Unknown artist",title:clean||"Untitled"}};

export default function App(){
 const [tab,setTab]=useState<Tab>("home"),[tracks,setTracks]=useState<StoredTrack[]>([]),[selected,setSelected]=useState<StoredTrack|null>(null),[playing,setPlaying]=useState(false),[full,setFull]=useState(false),[queueOpen,setQueueOpen]=useState(false),[queue,setQueue]=useState<StoredTrack[]>([]),[favorites,setFavorites]=useState<string[]>(()=>stored("mfa:favorites")),[recent,setRecent]=useState<string[]>(()=>stored("mfa:recent")),[query,setQuery]=useState(""),[openQuery,setOpenQuery]=useState(""),[results,setResults]=useState<Track[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[shuffle,setShuffle]=useState(false),[repeat,setRepeat]=useState<RepeatMode>("off");
 const audio=useRef(new Audio()),input=useRef<HTMLInputElement>(null);
 useEffect(()=>{listTracks().then(setTracks)},[]);
 useEffect(()=>localStorage.setItem("mfa:favorites",JSON.stringify(favorites)),[favorites]);
 useEffect(()=>localStorage.setItem("mfa:recent",JSON.stringify(recent)),[recent]);
 useEffect(()=>{if(message){const t=setTimeout(()=>setMessage(""),2200);return()=>clearTimeout(t)}},[message]);
 const ordered=useMemo(()=>[...tracks].sort((a,b)=>b.addedAt-a.addedAt),[tracks]);
 const filtered=useMemo(()=>ordered.filter(t=>(t.title+" "+t.artist+" "+t.album).toLowerCase().includes(query.toLowerCase())),[ordered,query]);
 const recentTracks=useMemo(()=>recent.map(id=>tracks.find(t=>t.id===id)).filter(Boolean) as StoredTrack[],[recent,tracks]);
 const favoriteTracks=useMemo(()=>tracks.filter(t=>favorites.includes(t.id)),[tracks,favorites]);
 const albums=useMemo(()=>{const seen=new Set<string>();return ordered.filter(t=>{const k=(t.album||"Local music")+"|"+(t.artist||"");if(seen.has(k))return false;seen.add(k);return true})},[ordered]);
 const artists=useMemo(()=>{const seen=new Set<string>();return ordered.filter(t=>{const k=t.artist||"Unknown artist";if(seen.has(k))return false;seen.add(k);return true})},[ordered]);
 const play=async(t:StoredTrack,resetQueue=true)=>{const b=await getBlob(t.blobId);if(!b){setMessage("Audio file unavailable.");return}if(resetQueue){const i=ordered.findIndex(x=>x.id===t.id);setQueue(ordered.slice(i+1))}audio.current.src=URL.createObjectURL(b);audio.current.load();setSelected(t);setRecent(x=>[t.id,...x.filter(i=>i!==t.id)].slice(0,30));try{await audio.current.play()}catch{}};
 const toggle=async()=>{if(!selected){if(ordered[0])await play(ordered[0]);return}if(audio.current.paused)await audio.current.play().catch(()=>{});else audio.current.pause()};
 const next=async(dir=1)=>{if(!selected||!ordered.length)return;if(dir===1&&queue.length){const [n,...rest]=queue;setQueue(rest);await play(n,false);return}if(shuffle){const pool=ordered.filter(x=>x.id!==selected.id);if(pool.length)await play(pool[Math.floor(Math.random()*pool.length)],false);return}const i=ordered.findIndex(t=>t.id===selected.id);if(dir===1&&repeat==="off"&&i===ordered.length-1){setPlaying(false);return}await play(ordered[(i+dir+ordered.length)%ordered.length],false)};
 const onEnded=async()=>{if(repeat==="one"){audio.current.currentTime=0;await audio.current.play().catch(()=>{});return}await next(1)};
 useEffect(()=>{const a=audio.current,p=()=>setPlaying(true),q=()=>setPlaying(false);a.addEventListener("play",p);a.addEventListener("pause",q);a.addEventListener("ended",onEnded);return()=>{a.removeEventListener("play",p);a.removeEventListener("pause",q);a.removeEventListener("ended",onEnded)}},[selected,queue,shuffle,repeat,ordered]);
 useEffect(()=>{const ms=navigator.mediaSession;if(!ms)return;try{ms.metadata=selected?new MediaMetadata({title:selected.title,artist:selected.artist,album:selected.album,artwork:selected.artworkUrl?[{src:selected.artworkUrl}]:[]}):null;ms.setActionHandler("play",()=>audio.current.play());ms.setActionHandler("pause",()=>audio.current.pause());ms.setActionHandler("nexttrack",()=>next(1));ms.setActionHandler("previoustrack",()=>next(-1));ms.setActionHandler("seekbackward",()=>{audio.current.currentTime=Math.max(0,audio.current.currentTime-10)});ms.setActionHandler("seekforward",()=>{audio.current.currentTime=Math.min(audio.current.duration,audio.current.currentTime+10)});}catch{}},[selected,queue,shuffle,repeat,ordered]);
 const fav=(id:string)=>setFavorites(x=>x.includes(id)?x.filter(i=>i!==id):[...x,id]);
 const addQueue=(t:StoredTrack)=>{setQueue(q=>q.some(x=>x.id===t.id)?q:[...q,t]);setMessage("Added to queue")};
 const remove=async(t:StoredTrack)=>{if(!window.confirm("Remove this song from Music For All?"))return;await deleteTrack(t.id,t.blobId);setTracks(await listTracks());setFavorites(x=>x.filter(id=>id!==t.id));setRecent(x=>x.filter(id=>id!==t.id));setQueue(x=>x.filter(x=>x.id!==t.id));if(selected?.id===t.id){audio.current.pause();setSelected(null);setPlaying(false)}setMessage("Removed from library")};
 const importFiles=async(e:ChangeEvent<HTMLInputElement>)=>{const fs=Array.from(e.target.files||[]);if(!fs.length)return;setBusy(true);for(const f of fs){const id=uid(),blobId=uid(),meta=parseFilename(f.name),t:StoredTrack={id,blobId,title:meta.title,artist:meta.artist,album:"Local music",source:"local",addedAt:Date.now()};try{const p=new Audio();p.src=URL.createObjectURL(f);await new Promise<void>(r=>{const done=()=>{t.duration=Number.isFinite(p.duration)?p.duration:undefined;r()};p.onloadedmetadata=done;p.onerror=()=>r();setTimeout(done,1800)});await saveTrack(t,f);setTracks(await listTracks())}catch{setMessage("Could not import "+f.name)}}setBusy(false);setMessage(fs.length+" "+(fs.length===1?"song":"songs")+" added");e.target.value=""};
 const searchOpen=async()=>{if(!openQuery.trim())return;setBusy(true);try{setResults(await searchOpenMusic(openQuery))}catch{setMessage("Open music search failed")}finally{setBusy(false)}};
 const keep=async(t:Track)=>{if(!t.audioUrl)return;try{const r=await fetch(t.audioUrl);if(!r.ok)throw 0;const b=await r.blob(),st:StoredTrack={...t,id:"local:"+uid(),blobId:uid(),addedAt:Date.now()};await saveTrack(st,b);setTracks(await listTracks());setMessage("Saved for offline listening")}catch{setMessage("This source cannot be downloaded here")}};
 const nav=(t:Tab)=>{setTab(t);window.scrollTo({top:0,behavior:"smooth"})};
 if(full&&selected)return <Player t={selected} playing={playing} toggle={toggle} next={next} close={()=>setFull(false)} favorite={favorites.includes(selected.id)} fav={()=>fav(selected.id)} audio={audio.current} queue={queue} openQueue={()=>setQueueOpen(true)} queueOpen={queueOpen} closeQueue={()=>setQueueOpen(false)} play={play} shuffle={shuffle} setShuffle={setShuffle} repeat={repeat} setRepeat={setRepeat}/>;
 return <div className="app">
  <header className="topbar"><button className="brand" onClick={()=>nav("home")}><b>M</b><span>Music For All</span></button><div className="top-search"><Icon n="search"/><input value={query} onChange={e=>{setQuery(e.target.value);if(tab!=="library")setTab("library")}} placeholder="What do you want to play?"/>{query&&<button className="clear-search" onClick={()=>setQuery("")}>×</button>}</div><button className="add" onClick={()=>input.current?.click()} aria-label="Import music"><Icon n="plus" s={22}/></button></header>
  <aside className="sidebar"><button className={tab==="home"?"active":""} onClick={()=>nav("home")}><Icon n="home"/><span>Home</span></button><button className={tab==="explore"?"active":""} onClick={()=>nav("explore")}><Icon n="search"/><span>Search</span></button><button className={tab==="library"?"active":""} onClick={()=>nav("library")}><Icon n="library"/><span>Your Library</span></button><div className="side-divider"/><button onClick={()=>{nav("library");setQuery("")}}><Icon n="clock"/><span>Recently added</span></button><button onClick={()=>{nav("library");setQuery("__liked__")}}><Icon n="heart"/><span>Liked Songs</span></button><button onClick={()=>input.current?.click()}><Icon n="plus"/><span>Add local music</span></button><div className="side-bottom"><button className={tab==="settings"?"active":""} onClick={()=>nav("settings")}><Icon n="settings"/><span>Settings</span></button></div></aside>
  <input ref={input} hidden type="file" accept="audio/*" multiple onChange={importFiles}/>
  <main>{tab==="home"&&<Home tracks={tracks} recent={recentTracks} favorites={favoriteTracks} albums={albums} artists={artists} selected={selected} playing={playing} play={play} toggle={toggle} next={next} fav={fav} openQueue={()=>setQueueOpen(true)} importMusic={()=>input.current?.click()} explore={()=>nav("explore")}/>}
   {tab==="library"&&<Library tracks={query==="__liked__"?favoriteTracks:filtered} allTracks={tracks} albums={albums} artists={artists} selected={selected} playing={playing} query={query==="__liked__"?"":query} setQuery={setQuery} play={play} toggle={toggle} fav={fav} favorites={favorites} addQueue={addQueue} remove={remove} importMusic={()=>input.current?.click()}/>}
   {tab==="explore"&&<Explore query={openQuery} setQuery={setOpenQuery} search={searchOpen} results={results} busy={busy} keep={keep}/>}
   {tab==="settings"&&<Settings tracks={tracks} importMusic={()=>input.current?.click()}/>}</main>
  {selected&&<Mini t={selected} playing={playing} toggle={toggle} open={()=>setFull(true)} queue={()=>setQueueOpen(true)}/>}
  <nav className="bottom-nav"><button className={tab==="home"?"on":""} onClick={()=>nav("home")}><Icon n="home"/><span>Home</span></button><button className={tab==="explore"?"on":""} onClick={()=>nav("explore")}><Icon n="search"/><span>Search</span></button><button className={tab==="library"?"on":""} onClick={()=>nav("library")}><Icon n="library"/><span>Library</span></button><button className={tab==="settings"?"on":""} onClick={()=>nav("settings")}><Icon n="settings"/><span>Settings</span></button></nav>
  {queueOpen&&<Queue tracks={queue} selected={selected} play={play} close={()=>setQueueOpen(false)}/>} {message&&<div className="toast">{message}</div>} {busy&&<div className="loading"><span/></div>}
 </div>;
}

function Section({title,action,children}:{title:string;action?:string;children:ReactNode}){return <section className="shelf"><div className="shelf-head"><h2>{title}</h2>{action&&<button>{action}<span>›</span></button>}</div>{children}</section>}
function Cards({tracks,play}:{tracks:StoredTrack[];play:(t:StoredTrack)=>void}){return <div className="rail">{tracks.map(t=><button className="music-card" key={t.id} onClick={()=>play(t)}><div className="card-art"><Art t={t}/><span className="card-play"><Icon n="play" s={17}/></span></div><b>{t.title}</b><small>{t.artist}</small></button>)}</div>}
function Home({tracks,recent,favorites,albums,artists,selected,playing,play,toggle,importMusic,explore}: {tracks:StoredTrack[];recent:StoredTrack[];favorites:StoredTrack[];albums:StoredTrack[];artists:StoredTrack[];selected:StoredTrack|null;playing:boolean;play:(t:StoredTrack)=>void;toggle:()=>void;next:(dir?:number)=>void;fav:(id:string)=>void;openQueue:()=>void;importMusic:()=>void;explore:()=>void}){
 const recentAdded=useMemo(()=>[...tracks].sort((a,b)=>b.addedAt-a.addedAt).slice(0,12),[tracks]);
 const featured=selected||recentAdded[0];
 const topArtists=artists.slice(0,7);
 const quick=useMemo(()=>[...recent,...favorites,...recentAdded].filter((t,i,a)=>t&&a.findIndex(x=>x.id===t.id)===i).slice(0,6),[recent,favorites,recentAdded]);
 const topTracks=useMemo(()=>[...tracks].sort((a,b)=>Number(b.addedAt)-Number(a.addedAt)).slice(0,5),[tracks]);
 return <section className="home">
  <div className="home-heading"><div><span className="eyebrow">YOUR OFFLINE MUSIC</span><h1>Good evening.</h1></div><button className="home-add" onClick={importMusic}><Icon n="plus" s={17}/> Add music</button></div>
  {featured?<div className="feature-layout">
   <div className="feature-hero">
    <div className="feature-image"><Art t={featured} large/></div>
    <div className="feature-gradient"/>
    <div className="feature-copy"><span>{selected?"CONTINUE LISTENING":"RECENTLY ADDED"}</span><h2>{featured.title}</h2><p>{featured.artist}<i> · </i>{featured.album}</p><div className="feature-actions"><button className="primary" onClick={()=>selected?toggle():play(featured)}><Icon n={playing&&selected?.id===featured.id?"pause":"play"} s={16}/>{playing&&selected?.id===featured.id?"Pause":"Play"}</button><button className={"feature-like "+(favorites.some(x=>x.id===featured.id)?"on":"")} onClick={()=>fav(featured.id)}><Icon n="heart" s={18}/></button></div></div>
   </div>
   <aside className="home-player"><div className="home-player-head"><span>NOW PLAYING</span><button onClick={()=>{}}><Icon n="more" s={18}/></button></div><div className="home-player-art"><Art t={featured} large/></div><div className="home-player-meta"><div><h3>{featured.title}</h3><p>{featured.artist}</p></div><span>{fmt(featured.duration)}</span></div><div className="home-progress"><i style={{width:playing?"42%":"0%"}}/></div><div className="home-player-times"><span>0:00</span><span>{fmt(featured.duration)}</span></div><div className="home-controls"><button><Icon n="shuffle" s={17}/></button><button onClick={()=>play(featured)}><Icon n="prev" s={18}/></button><button className="home-play" onClick={toggle}><Icon n={playing?"pause":"play"} s={20}/></button><button onClick={()=>next(1)}><Icon n="next" s={18}/></button><button><Icon n="repeat" s={17}/></button></div><button className="home-queue" onClick={openQueue}><Icon n="queue" s={16}/> Playing next <span>›</span></button>
   </aside>
  </div>:<div className="home-empty-hero"><div><span className="eyebrow">YOUR OFFLINE MUSIC PLAYER</span><h2>Your music,<br/>all in one place.</h2><p>Import your collection and Music For All turns it into a streaming-style library that works offline.</p><div className="hero-actions"><button className="primary" onClick={importMusic}><Icon n="plus" s={16}/> Import music</button><button className="ghost" onClick={explore}>Explore open music</button></div></div><div className="empty-art"><Art large/></div></div>}
  {tracks.length>0&&<>
   <Section title="Quick picks" action="View all"><div className="home-quick-grid">{quick.map(t=><button key={t.id} className="home-quick" onClick={()=>play(t)}><div className="home-quick-art"><Art t={t}/><span><Icon n="play" s={14}/></span></div><div><b>{t.title}</b><small>{t.artist}</small></div><i><Icon n="more" s={17}/></i></button>)}</div></Section>
   {topArtists.length>0&&<Section title="Top artists" action="See all"><div className="home-artists">{topArtists.map(t=><button key={t.id} onClick={()=>play(t)}><div className="home-artist-art"><Art t={t}/></div><b>{t.artist}</b><small>{tracks.filter(x=>x.artist===t.artist).length} {tracks.filter(x=>x.artist===t.artist).length===1?"song":"songs"}</small></button>)}</div></Section>}
   <div className="home-two-col">
    <Section title="Recently added" action="See all"><Cards tracks={recentAdded.slice(0,8)} play={play}/></Section>
    <Section title="Your albums" action="See all"><Cards tracks={albums.slice(0,8)} play={play}/></Section>
   </div>
   <Section title="Songs" action="Open library"><div className="home-song-list">{topTracks.map((t,i)=><button key={t.id} onClick={()=>play(t)}><span className="home-song-index">{String(i+1).padStart(2,"0")}</span><Art t={t}/><span className="home-song-copy"><b>{t.title}</b><small>{t.artist}</small></span><span className="home-song-album">{t.album}</span><time>{fmt(t.duration)}</time><i><Icon n="play" s={14}/></i></button>)}</div></Section>
  </>}
  <Section title="Open music"><div className="open-promo"><div><span className="eyebrow">PUBLIC DOMAIN + CC0</span><h2>Find music you can actually keep.</h2><p>Explore open recordings, then save eligible tracks into the same offline library.</p></div><button onClick={explore}>Explore <span>›</span></button></div></Section>
 </section>;
}
function Library({tracks,allTracks,albums,artists,selected,playing,query,setQuery,play,toggle,fav,favorites:favIds,addQueue,remove,importMusic}:{tracks:StoredTrack[];allTracks:StoredTrack[];albums:StoredTrack[];artists:StoredTrack[];selected:StoredTrack|null;playing:boolean;query:string;setQuery:(s:string)=>void;play:(t:StoredTrack)=>void;toggle:()=>void;fav:(id:string)=>void;favorites:string[];addQueue:(t:StoredTrack)=>void;remove:(t:StoredTrack)=>void;importMusic:()=>void}){
 const [view,setView]=useState<ViewMode>("songs");
 return <section className="library-page"><div className="page-title"><div><span className="eyebrow">YOUR LIBRARY</span><h1>All your music.</h1></div><strong>{allTracks.length}<small>{allTracks.length===1?"song":"songs"}</small></strong></div>
 <div className="library-toolbar"><div className="library-search"><Icon n="search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search songs, artists or albums"/></div><button className="import-inline" onClick={importMusic}><Icon n="plus" s={17}/> Add music</button></div>
 <div className="library-tabs"><button className={view==="songs"?"on":""} onClick={()=>setView("songs")}>Songs</button><button className={view==="albums"?"on":""} onClick={()=>setView("albums")}>Albums</button><button className={view==="artists"?"on":""} onClick={()=>setView("artists")}>Artists</button></div>
 {selected&&<div className="library-player"><Art t={selected}/><div><span className="eyebrow">PLAYING NOW</span><b>{selected.title}</b><small>{selected.artist}</small></div><button className="play-main" onClick={toggle}><Icon n={playing?"pause":"play"} s={18}/></button><button className={"heart "+(favIds.includes(selected.id)?"on":"")} onClick={()=>fav(selected.id)}><Icon n="heart"/></button></div>}
 {view==="songs"&&<SongList tracks={tracks} selected={selected} playing={playing} fav={fav} favIds={favIds} play={play} addQueue={addQueue} remove={remove} allTracks={allTracks}/>}
 {view==="albums"&&<div className="album-grid">{albums.map(t=><button key={t.id} onClick={()=>play(t)}><div className="card-art"><Art t={t}/><span className="card-play"><Icon n="play" s={17}/></span></div><b>{t.album||"Local music"}</b><small>{t.artist}</small></button>)}</div>}
 {view==="artists"&&<div className="artist-grid">{artists.map(t=>{const count=allTracks.filter(x=>x.artist===t.artist).length;return <button key={t.id} onClick={()=>play(t)}><Art t={t}/><b>{t.artist}</b><small>{count} {count===1?"song":"songs"}</small></button>})}</div>}
 </section>;
}
function SongList({tracks,selected,playing,fav,favIds,play,addQueue,remove}:{tracks:StoredTrack[];selected:StoredTrack|null;playing:boolean;fav:(id:string)=>void;favIds:string[];play:(t:StoredTrack)=>void;addQueue:(t:StoredTrack)=>void;remove:(t:StoredTrack)=>void;allTracks:StoredTrack[]}){
 return <div className="song-list"><div className="song-head"><span>#</span><span>Title</span><span>Album</span><span>Time</span><span/></div>{tracks.map((t,i)=><div className={"song-row"+(selected?.id===t.id?" current":"")} key={t.id}><span className="index">{String(i+1).padStart(2,"0")}</span><button className="row-art" onClick={()=>play(t)}><Art t={t}/><i><Icon n={selected?.id===t.id&&playing?"pause":"play"} s={15}/></i></button><button className="row-info" onClick={()=>play(t)}><b>{t.title}</b><small>{t.artist}</small></button><span className="row-album">{t.album}</span><time>{fmt(t.duration)}</time><div className="row-actions"><button className={"heart "+(favIds.includes(t.id)?"on":"")} onClick={()=>fav(t.id)}><Icon n="heart" s={17}/></button><button onClick={()=>addQueue(t)} aria-label="Add to queue"><Icon n="queue" s={18}/></button><button onClick={()=>remove(t)} aria-label="Remove song"><Icon n="trash" s={17}/></button></div></div>)}{!tracks.length&&<div className="no-results"><h2>Your library is empty.</h2><p>Import music to start building your collection.</p></div>}</div>;
}
function Explore({query,setQuery,search,results,busy,keep}:{query:string;setQuery:(s:string)=>void;search:()=>void;results:Track[];busy:boolean;keep:(t:Track)=>void}){return <section className="search-page"><span className="eyebrow">OPEN MUSIC</span><h1>Search the<br/><em>open catalogue.</em></h1><p className="intro">Discovery can be broad. Download eligibility stays narrow: Music For All only offers Public Domain and CC0 recordings for offline saving.</p><form onSubmit={e=>{e.preventDefault();search()}}><Icon n="search"/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search artists, recordings, instruments..."/><button>Search</button></form>{results.length===0&&!busy?<div className="search-start"><span>OPEN DISCOVERY</span><h2>Field recordings.<br/>Old rooms. New sounds.</h2><p>Search a rights-aware catalogue and keep what is explicitly eligible.</p></div>:<div className="result-grid">{results.map(t=><article key={t.id}><div className="result-art"><Art t={t}/><button onClick={()=>t.audioUrl&&window.open(t.audioUrl,"_blank")}><Icon n="play" s={18}/></button></div><div className="result-copy"><b>{t.title}</b><small>{t.artist}</small><span>{t.license==="cc0"?"CC0":"PUBLIC DOMAIN"} · {t.provider||"Openverse"}</span><button className="keep" onClick={()=>keep(t)}><Icon n="download" s={14}/> Keep offline</button></div></article>)}</div>}</section>}

function Settings({tracks,importMusic}:{tracks:StoredTrack[];importMusic:()=>void}){return <section className="settings-page"><span className="eyebrow">SETTINGS</span><h1>Your music.<br/><em>Your rules.</em></h1><div className="settings-card"><div><b>{tracks.length}</b><span>{tracks.length===1?"song":"songs"} stored on this device</span></div><button onClick={importMusic}><Icon n="plus"/><span>Import music</span></button></div><div className="settings-groups"><div><span>STORAGE</span><b>Local-first playback</b><p>Imported audio is stored in browser-managed local storage. It does not require an account.</p></div><div><span>DISCOVERY</span><b>Open music is separate</b><p>Public Domain and CC0 recordings can be saved into the same local library when the source permits downloading.</p></div><div><span>DESIGN SYSTEM</span><b>Inter · dark surfaces · artwork-led</b><p>Built for dense browsing, large artwork, persistent playback and fast navigation across desktop and mobile.</p></div></div></section>}

function Mini({t,playing,toggle,open,queue}:{t:StoredTrack;playing:boolean;toggle:()=>void;open:()=>void;queue:()=>void}){return <div className="mini"><button className="mini-art" onClick={open}><Art t={t}/></button><button className="mini-info" onClick={open}><b>{t.title}</b><small>{t.artist}</small></button><button className="mini-play" onClick={toggle}><Icon n={playing?"pause":"play"} s={17}/></button><button className="mini-queue" onClick={queue}><Icon n="queue"/></button></div>}

function Queue({tracks,selected,play,close}:{tracks:StoredTrack[];selected:StoredTrack|null;play:(t:StoredTrack,resetQueue?:boolean)=>void;close:()=>void}){return <div className="shade" onClick={close}><aside className="queue-panel" onClick={e=>e.stopPropagation()}><header><div><span className="eyebrow">PLAYING NEXT</span><h2>Queue</h2></div><button onClick={close}>Done</button></header>{tracks.length?tracks.map(t=><button className={t.id===selected?.id?"current":""} onClick={()=>{play(t,false);close()}} key={t.id}><Art t={t}/><span><b>{t.title}</b><small>{t.artist}</small></span><em>{fmt(t.duration)}</em></button>):<div className="queue-empty"><Icon n="queue" s={28}/><h3>Nothing queued</h3><p>Add songs from your library and they will play here.</p></div>}</aside></div>}

function Player({t,playing,toggle,next,close,favorite,fav,audio,queue,openQueue,queueOpen,closeQueue,play,shuffle,setShuffle,repeat,setRepeat}:{t:StoredTrack;playing:boolean;toggle:()=>void;next:(d?:number)=>void;close:()=>void;favorite:boolean;fav:()=>void;audio:HTMLAudioElement;queue:StoredTrack[];openQueue:()=>void;queueOpen:boolean;closeQueue:()=>void;play:(t:StoredTrack,resetQueue?:boolean)=>void;shuffle:boolean;setShuffle:(v:boolean)=>void;repeat:RepeatMode;setRepeat:(v:RepeatMode)=>void}){
 const [pos,setPos]=useState(0),[dur,setDur]=useState(t.duration||0);
 useEffect(()=>{const u=()=>{setPos(audio.currentTime);if(Number.isFinite(audio.duration))setDur(audio.duration)};u();audio.addEventListener("timeupdate",u);audio.addEventListener("loadedmetadata",u);return()=>{audio.removeEventListener("timeupdate",u);audio.removeEventListener("loadedmetadata",u)}},[audio,t]);
 const cycle=()=>setRepeat(repeat==="off"?"all":repeat==="all"?"one":"off");
 return <div className="player"><div className="player-bg"><Art t={t} large/></div><header><button onClick={close}><Icon n="back"/></button><span>NOW PLAYING</span><button onClick={openQueue}><Icon n="queue"/></button></header><main><div className="player-art"><Art t={t} large/></div><div className="player-meta"><div><h1>{t.title}</h1><p>{t.artist}</p><small>{t.album}</small></div><button className={"heart "+(favorite?"on":"")} onClick={fav}><Icon n="heart" s={24}/></button></div><input aria-label="Playback position" className="range" type="range" min="0" max={dur||1} value={Math.min(pos,dur||1)} onChange={e=>{audio.currentTime=+e.target.value;setPos(+e.target.value)}}/><div className="times"><span>{fmt(pos)}</span><span>-{fmt(Math.max(0,dur-pos))}</span></div><div className="transport"><button className={shuffle?"control-on":""} onClick={()=>setShuffle(!shuffle)}><Icon n="shuffle"/></button><button onClick={()=>next(-1)}><Icon n="prev"/></button><button className="big-play" onClick={toggle}><Icon n={playing?"pause":"play"} s={28}/></button><button onClick={()=>next(1)}><Icon n="next"/></button><button className={repeat!=="off"?"control-on":""} onClick={cycle}><Icon n="repeat"/></button></div><div className="player-footer"><button onClick={openQueue}><Icon n="queue"/> <span>{queue.length} next</span></button><button className={favorite?"control-on":""} onClick={fav}><Icon n="heart"/></button></div></main>{queueOpen&&<Queue tracks={queue} selected={t} play={play} close={closeQueue}/>}</div>;
}
