import {useEffect,useMemo,useRef,useState} from "react";
import type {ChangeEvent} from "react";
import type {StoredTrack,Tab,Track} from "./types";
import {getBlob,listTracks,saveTrack} from "./lib/db";
import {searchOpenMusic} from "./lib/openverse";

const Icon=({n,s=21}:{n:string;s?:number})=><svg width={s} height={s} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d={n==="search"?"M10.5 4a6.5 6.5 0 1 0 0 13 6.5 6.5 0 0 0 0-13ZM16 16l5 5":n==="plus"?"M12 5v14M5 12h14":n==="back"?"m15 5-7 7 7 7":n==="queue"?"M4 6h11M4 12h11M4 18h7m5-3 4 3-4 3":n==="heart"?"M20.8 8.9c0 5.5-8.8 10.1-8.8 10.1S3.2 14.4 3.2 8.9A5 5 0 0 1 12 5.4a5 5 0 0 1 8.8 3.5":n==="play"?"M8 5v14l11-7z":n==="pause"?"M7 5h4v14H7zM13 5h4v14h-4z":n==="next"?"M5 5v14l9-7zM18 5v14":n==="prev"?"M19 5v14l-9-7zM6 5v14":"M12 3v18M3 12h18"}/></svg>;
const Art=({t,large=false}:{t?:Track;large?:boolean})=>{const seed=(t?.title||"Music").split("").reduce((a,c)=>a+c.charCodeAt(0),0);const ps=[["#d9ff48","#111218"],["#ff725c","#f2d8d0"],["#728dff","#111218"],["#f1d96b","#22271b"],["#bd99ff","#1b1522"]];const [a,b]=ps[seed%ps.length];return <div className={"art "+(large?"large":"")} style={{"--a":a,"--b":b} as any}><span>{(t?.title||"M").charAt(0).toUpperCase()}</span></div>};
const fmt=(n=0)=>Number.isFinite(n)&&n>=0?Math.floor(n/60)+":"+String(Math.floor(n%60)).padStart(2,"0"):"—";
const stored=(k:string)=>{try{const x=JSON.parse(localStorage.getItem(k)||"[]");return Array.isArray(x)?x:[]}catch{return[]}};
const uid=()=>crypto.randomUUID?.()||String(Date.now()+Math.random());

export default function App(){
 const [tab,setTab]=useState<Tab>("home"),[tracks,setTracks]=useState<StoredTrack[]>([]),[selected,setSelected]=useState<StoredTrack|null>(null),[playing,setPlaying]=useState(false),[full,setFull]=useState(false),[queue,setQueue]=useState(false),[favorites,setFavorites]=useState<string[]>(()=>stored("mfa:favorites")),[recent,setRecent]=useState<string[]>(()=>stored("mfa:recent")),[query,setQuery]=useState(""),[openQuery,setOpenQuery]=useState(""),[results,setResults]=useState<Track[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const audio=useRef(new Audio()),input=useRef<HTMLInputElement>(null);
 useEffect(()=>{listTracks().then(setTracks)},[]);useEffect(()=>localStorage.setItem("mfa:favorites",JSON.stringify(favorites)),[favorites]);useEffect(()=>localStorage.setItem("mfa:recent",JSON.stringify(recent)),[recent]);useEffect(()=>{if(message){const t=setTimeout(()=>setMessage(""),2200);return()=>clearTimeout(t)}},[message]);
 const ordered=useMemo(()=>[...tracks].sort((a,b)=>b.addedAt-a.addedAt),[tracks]), filtered=useMemo(()=>ordered.filter(t=>(t.title+" "+t.artist+" "+t.album).toLowerCase().includes(query.toLowerCase())),[ordered,query]);
 const play=async(t:StoredTrack)=>{const b=await getBlob(t.blobId);if(!b){setMessage("Audio file unavailable.");return}audio.current.src=URL.createObjectURL(b);await audio.current.play().catch(()=>{});setSelected(t);setPlaying(true);setRecent(x=>[t.id,...x.filter(i=>i!==t.id)].slice(0,10))};
 const toggle=async()=>{if(!selected){if(ordered[0])play(ordered[0]);return}if(audio.current.paused)await audio.current.play().catch(()=>{});else audio.current.pause()};
 const next=(dir=1)=>{if(!selected||!ordered.length)return;const i=ordered.findIndex(t=>t.id===selected.id);play(ordered[(i+dir+ordered.length)%ordered.length])};
 useEffect(()=>{const a=audio.current;const p=()=>setPlaying(true),q=()=>setPlaying(false),e=()=>next(1);a.addEventListener("play",p);a.addEventListener("pause",q);a.addEventListener("ended",e);return()=>{a.removeEventListener("play",p);a.removeEventListener("pause",q);a.removeEventListener("ended",e)}},[ordered,selected]);
 const fav=(id:string)=>setFavorites(x=>x.includes(id)?x.filter(i=>i!==id):[...x,id]);
 const importFiles=async(e:ChangeEvent<HTMLInputElement>)=>{const fs=Array.from(e.target.files||[]);if(!fs.length)return;setBusy(true);for(const f of fs){const id=uid(),blobId=uid(),t:StoredTrack={id,blobId,title:f.name.replace(/\.[^.]+$/,"").replace(/[_-]+/g," ").trim()||"Untitled",artist:"Unknown artist",album:"Local music",source:"local",addedAt:Date.now()};try{const p=new Audio();p.src=URL.createObjectURL(f);await new Promise<void>(r=>{const done=()=>{t.duration=Number.isFinite(p.duration)?p.duration:undefined;r()};p.onloadedmetadata=done;p.onerror=()=>r();setTimeout(done,1800)});await saveTrack(t,f);setTracks(await listTracks());setMessage("Added to your library.")}catch{setMessage("Could not import "+f.name)}}setBusy(false);e.target.value=""};
 const searchOpen=async()=>{if(!openQuery.trim())return;setBusy(true);try{setResults(await searchOpenMusic(openQuery))}catch{setMessage("Open music search failed.")}finally{setBusy(false)}};
 const keep=async(t:Track)=>{if(!t.audioUrl)return;try{const r=await fetch(t.audioUrl);if(!r.ok)throw 0;const b=await r.blob(),st:StoredTrack={...t,id:"local:"+uid(),blobId:uid(),addedAt:Date.now()};await saveTrack(st,b);setTracks(await listTracks());setMessage("Saved to your library.")}catch{setMessage("This source cannot be downloaded here.")}};
 if(full&&selected)return <Player t={selected} playing={playing} toggle={toggle} next={next} close={()=>setFull(false)} favorite={favorites.includes(selected.id)} fav={()=>fav(selected.id)} audio={audio.current} queue={ordered} openQueue={()=>setQueue(true)} queueOpen={queue} closeQueue={()=>setQueue(false)} play={play}/>;
 return <div className="app"><header><button className="brand" onClick={()=>setTab("home")}><b>M</b><span>music for all</span></button><button className="add" onClick={()=>input.current?.click()}><Icon n="plus" s={25}/></button></header><input ref={input} hidden type="file" accept="audio/*" multiple onChange={importFiles}/><main>
 {tab==="home"&&<Library tracks={filtered} recent={recent} selected={selected} playing={playing} query={query} setQuery={setQuery} play={play} toggle={toggle} fav={fav} favorites={favorites} importMusic={()=>input.current?.click()} explore={()=>setTab("explore")}/>}
 {tab==="explore"&&<Explore query={openQuery} setQuery={setOpenQuery} search={searchOpen} results={results} busy={busy} keep={keep}/>}
 {tab==="settings"&&<Settings tracks={tracks} importMusic={()=>input.current?.click()}/>}</main>
 {selected&&<Mini t={selected} playing={playing} toggle={toggle} open={()=>setFull(true)} queue={()=>setQueue(true)}/>}
 <nav><button className={tab==="home"?"on":""} onClick={()=>setTab("home")}><Icon n="queue"/><span>Library</span></button><button className={tab==="explore"?"on":""} onClick={()=>setTab("explore")}><Icon n="search"/><span>Explore</span></button><button className={tab==="settings"?"on":""} onClick={()=>setTab("settings")}><Icon n="plus"/><span>Settings</span></button></nav>
 {queue&&<Queue tracks={ordered} selected={selected} play={play} close={()=>setQueue(false)}/>} {message&&<div className="toast">{message}</div>}{busy&&<div className="loading"/>}</div>
}

function Library({tracks,recent,selected,playing,query,setQuery,play,toggle,fav,favorites,importMusic,explore}:{tracks:StoredTrack[];recent:string[];selected:StoredTrack|null;playing:boolean;query:string;setQuery:(s:string)=>void;play:(t:StoredTrack)=>void;toggle:()=>void;fav:(id:string)=>void;favorites:string[];importMusic:()=>void;explore:()=>void}){
 const rec=recent.map(id=>tracks.find(t=>t.id===id)).filter(Boolean) as StoredTrack[];
 return <section className="library"><div className="heading"><div><label>YOUR LIBRARY</label><h1>Your music.</h1></div><strong>{tracks.length}<small>{tracks.length===1?"song":"songs"}</small></strong></div><div className="searchbar"><Icon n="search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search your library"/></div>{tracks.length===0?<div className="empty"><Art/><div><label>LOCAL MUSIC PLAYER</label><h2>Nothing here <em>yet.</em></h2><p>Import the music already on your device. It stays here, without an account or feed.</p><button onClick={importMusic}>Import music</button><button className="link" onClick={explore}>Explore open music →</button></div></div>:<>{selected&&<section className="now"><Art t={selected}/><div><label>NOW PLAYING</label><h2>{selected.title}</h2><p>{selected.artist}</p><div><button className="circle" onClick={toggle}><Icon n={playing?"pause":"play"}/></button><button className={"heart "+(favorites.includes(selected.id)?"on":"")} onClick={()=>fav(selected.id)}><Icon n="heart"/></button></div></div></section>}{rec.length>0&&<section className="recent"><div className="section-head"><h2>Recently played</h2><span>{rec.length}</span></div><div className="cards">{rec.slice(0,6).map(t=><button onClick={()=>play(t)} key={t.id}><Art t={t}/><b>{t.title}</b><small>{t.artist}</small></button>)}</div></section>}<div className="section-head"><h2>All songs</h2><span>{tracks.length}</span></div><div className="songs">{tracks.map((t,i)=><div className="song" key={t.id}><button className="thumb" onClick={()=>play(t)}><Art t={t}/><i><Icon n={selected?.id===t.id&&playing?"pause":"play"} s={17}/></i></button><button className="song-info" onClick={()=>play(t)}><b>{t.title}</b><small>{t.artist} · {t.album}</small></button><em>{String(i+1).padStart(2,"0")}</em><button className={favorites.includes(t.id)?"heart on":"heart"} onClick={()=>fav(t.id)}><Icon n="heart" s={19}/></button><time>{fmt(t.duration)}</time></div>)}</div></>}</section>
}

function Explore({query,setQuery,search,results,busy,keep}:{query:string;setQuery:(s:string)=>void;search:()=>void;results:Track[];busy:boolean;keep:(t:Track)=>void}){return <section className="explore"><label>OPEN MUSIC</label><h1>Music worth <em>keeping.</em></h1><p className="intro">A small catalogue of public-domain and CC0 recordings. Search it when you want something outside your library.</p><form onSubmit={e=>{e.preventDefault();search()}}><Icon n="search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search recordings, instruments, places..."/><button>Search</button></form>{results.length===0&&!busy?<div className="discover"><span>01</span><h2>Search without a feed.</h2><p>Find a recording, listen to it, then decide whether it belongs in your library.</p></div>:<div className="open-grid">{results.map(t=><article key={t.id}><button className="open-art"><Art t={t}/><i><Icon n="play" s={18}/></i></button><div><b>{t.title}</b><small>{t.artist}</small></div><button className="keep" onClick={()=>keep(t)}>Keep</button><small className="license">{t.license==="cc0"?"CC0":"PUBLIC DOMAIN"} · {t.provider||"Openverse"}</small></article>)}</div>}</section>}

function Settings({tracks,importMusic}:{tracks:StoredTrack[];importMusic:()=>void}){return <section className="settings"><label>SETTINGS</label><h1>The player, <em>without the noise.</em></h1><p className="intro">Music For All is local-first. Your library belongs to this browser and no login is required.</p><div className="settings-list"><div><small>LIBRARY</small><b>{tracks.length} {tracks.length===1?"song":"songs"}</b><p>Stored locally on this device.</p></div><button onClick={importMusic}><small>LIBRARY</small><b>Import more music</b><p>Choose audio files from your device.</p><strong>＋</strong></button><div><small>OPEN MUSIC</small><b>Public Domain + CC0</b><p>Explore is deliberately separate from your private collection.</p></div></div><footer>Music For All <span>v0.3</span></footer></section>}

function Mini({t,playing,toggle,open,queue}:{t:StoredTrack;playing:boolean;toggle:()=>void;open:()=>void;queue:()=>void}){return <div className="mini"><button onClick={open} className="mini-art"><Art t={t}/></button><button onClick={open} className="mini-info"><b>{t.title}</b><small>{t.artist}</small></button><button onClick={toggle}><Icon n={playing?"pause":"play"}/></button><button onClick={queue}><Icon n="queue"/></button></div>}

function Queue({tracks,selected,play,close}:{tracks:StoredTrack[];selected:StoredTrack|null;play:(t:StoredTrack)=>void;close:()=>void}){return <div className="shade" onClick={close}><aside className="queue"><i/><header><div><label>UP NEXT</label><h2>Queue</h2></div><button onClick={close}>Done</button></header>{tracks.map(t=><button className={t.id===selected?.id?"current":""} onClick={()=>{play(t);close()}} key={t.id}><Art t={t}/><span><b>{t.title}</b><small>{t.artist}</small></span><em>{t.id===selected?.id?"Playing":fmt(t.duration)}</em></button>)}</aside></div>}

function Player({t,playing,toggle,next,close,favorite,fav,audio,queue,openQueue,queueOpen,closeQueue,play}:{t:StoredTrack;playing:boolean;toggle:()=>void;next:(d?:number)=>void;close:()=>void;favorite:boolean;fav:()=>void;audio:HTMLAudioElement;queue:StoredTrack[];openQueue:()=>void;queueOpen:boolean;closeQueue:()=>void;play:(t:StoredTrack)=>void}){const [pos,setPos]=useState(0),[dur,setDur]=useState(t.duration||0);useEffect(()=>{const u=()=>{setPos(audio.currentTime);if(Number.isFinite(audio.duration))setDur(audio.duration)};audio.addEventListener("timeupdate",u);audio.addEventListener("loadedmetadata",u);return()=>{audio.removeEventListener("timeupdate",u);audio.removeEventListener("loadedmetadata",u)}},[audio,t]);return <div className="player"><header><button onClick={close}><Icon n="back"/></button><span>NOW PLAYING</span><button onClick={openQueue}><Icon n="queue"/></button></header><main><Art t={t} large/><div className="player-title"><div><h1>{t.title}</h1><p>{t.artist}</p><small>{t.album}</small></div><button className={favorite?"heart on":"heart"} onClick={fav}><Icon n="heart"/></button></div><input className="range" type="range" min="0" max={dur||1} value={Math.min(pos,dur||1)} onChange={e=>{audio.currentTime=+e.target.value;setPos(+e.target.value)}}/><div className="times"><span>{fmt(pos)}</span><span>{fmt(Math.max(0,dur-pos))}</span></div><div className="transport"><button onClick={()=>next(-1)}><Icon n="prev"/></button><button className="big" onClick={toggle}><Icon n={playing?"pause":"play"} s={27}/></button><button onClick={()=>next(1)}><Icon n="next"/></button></div><button className="queue-link" onClick={openQueue}><Icon n="queue"/>Play queue <span>{queue.length}</span></button></main>{queueOpen&&<Queue tracks={queue} selected={t} play={play} close={closeQueue}/>}</div>}
